services:
  registry:
    image: registry:2
    container_name: registry
    restart: unless-stopped
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    volumes:
      - ./.docker/registry/auth:/auth:ro
      - registry-data:/data
    networks:
      - traefik-network
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-network
      - traefik.http.routers.registry.rule=Host(`${REGISTRY_HOSTNAME:?required}`)
      - traefik.http.routers.registry.entrypoints=https
      - traefik.http.routers.registry.tls.certresolver=cloudflare
      - traefik.http.routers.registry.service=registry
      - traefik.http.services.registry.loadbalancer.server.port=5000


volumes:
  registry-data:


networks:
  traefik-network:
    external: true
